package com.dnn.lot.mapper;

import com.dnn.lot.model.UmsResource;
import com.dnn.lot.model.UmsResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource
     *
     * @mbg.generated Mon Nov 29 18:38:07 CST 2021
     */
    long countByExample(UmsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource
     *
     * @mbg.generated Mon Nov 29 18:38:07 CST 2021
     */
    int deleteByExample(UmsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource
     *
     * @mbg.generated Mon Nov 29 18:38:07 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource
     *
     * @mbg.generated Mon Nov 29 18:38:07 CST 2021
     */
    int insert(UmsResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource
     *
     * @mbg.generated Mon Nov 29 18:38:07 CST 2021
     */
    int insertSelective(UmsResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource
     *
     * @mbg.generated Mon Nov 29 18:38:07 CST 2021
     */
    List<UmsResource> selectByExample(UmsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource
     *
     * @mbg.generated Mon Nov 29 18:38:07 CST 2021
     */
    UmsResource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource
     *
     * @mbg.generated Mon Nov 29 18:38:07 CST 2021
     */
    int updateByExampleSelective(@Param("record") UmsResource record, @Param("example") UmsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource
     *
     * @mbg.generated Mon Nov 29 18:38:07 CST 2021
     */
    int updateByExample(@Param("record") UmsResource record, @Param("example") UmsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource
     *
     * @mbg.generated Mon Nov 29 18:38:07 CST 2021
     */
    int updateByPrimaryKeySelective(UmsResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource
     *
     * @mbg.generated Mon Nov 29 18:38:07 CST 2021
     */
    int updateByPrimaryKey(UmsResource record);
}